### ISSUE TITLE
Create Mesh Class

### ISSUE THREAD

**Issue by Connor1476** [myerspat/rbm-diffusion#14]
## Background
In order to make a 1 speed 1D diffusion problem we need to create a 1D finite mesh structure with base capabilities. This will Create a mesh and return the Migration Matrix and Fission Matrix. The constructor will take in variables in order to make the mesh while the run function will take in cross sections and the diffusion coefficient in order to iterate over the mesh and solve for the Migration(M) and Fission(F) Matrix.

## Tasks
Describe what work is expected to be performed as a part of this issue
Make a mesh class -> Specifically a 1D Finite centered Mesh
Methods to be made are 
- [ ] Make a constructor for the mesh that will take in the inherent mesh structures and some more ie. distance, partition amount, M, F, left boundary condition, and right boundary condition.
- [ ] run() which find the Migration and Fission Matrix given cross sections of fission and absorption along with the diffusion coefficient.
- [ ] get methods in order to return the private variable  Migration and Fission Matrices from outside the class

## Definition of Done
Done when Migration and Fission outputs pass tests. This Mesh is not the most generalized there is, but it is means for a proof of concept for RBM and once we get that then more in detail planning will happen for a generalized mesh structure.
