### ISSUE TITLE
Cmake framework

### ISSUE THREAD

**Issue by myerspat** [myerspat/rbm-diffusion#3]
## Background
The original plan was to make a makefile and add the code there to compile but since this is likely to get complex quickly we need CMake. This will allow us to add new files and unit tests for respective functions easily. 

## Tasks
- [x] Add a unit testing framework for the source, examples, and testing directories
- [x] Create a testing directory with the capability to add new tests
- [x] Add a unit test for the matrix

## Definition of Done
The framework is put in place with easy expandability to new source files/ unit tests and can successfully compile the existing code base. Testing is added with easy expandability.
