### ISSUE TITLE
Change inheritance framework to use enum as opposed to child classes in RBM

### ISSUE THREAD

**Issue by myerspat** [myerspat/rbm-diffusion#40]
## Background
The current framework for the `RBM` class anticipates a child class for each perturbed parameter (absorption XS, diffusion, and nu_fission XS). However, this could be more easily handled through a parameter enum. A variable can then be set to the correct enumeration value based on the parsing of the XML "parameter" attribute in the training node.

## Tasks
- [x] Child class `PerturbAbsorption` and virtual qualifiers are deleted
- [x] The `RBM` class name is changed to `Perturb` for clarity
- [x] The changes in class structure and name are adopted to the other files and all tests pass

## Definition of Done
`PerturbAbsorption` is no longer used along with the inheritance structure. All `PerturbAbsoprtion` class types are changed to `Perturb`  and all tests pass.
