### ISSUE TITLE
Create `constructFineGrid` function

### ISSUE THREAD

**Issue by myerspat** [myerspat/rbm-diffusion#45]
## Background
Now that the course mesh has can be constructed the fine mesh can be constructed using the bins in the x and y direction and position in the course mesh. 

## Tasks
- [ ] Define the `constructFineGrid` function
- [ ] Test the function
- [ ] Define the `constructMesh` function

## Definition of Done
Both functions are defined and `constructFineMesh passes the tests.
