### ISSUE TITLE
Change input XML parsing functions to use new mesh structure

### ISSUE THREAD

**Issue by myerspat** [myerspat/rbm-diffusion#47]
## Background
The parsing functions were specifically written for the old mesh structure, while much of the same data is still used, the structure of the XML input file needs to be changed. Therefore, the parsing functions for it must be changed as well.

## Tasks
- [x] Change the functions to adopt the new mesh structure
- [x] Uncomment tests and change as needed
- [x] Change `_cell_id` to `_element_id` for clarity
- [x] Uncomment functions used in main

## Definition of Done
All of the above is done and the tests are passing.
