### ISSUE TITLE
Implement `changeMaterial` and `setParameter` functions

### ISSUE THREAD

**Issue by myerspat** [myerspat/rbm-diffusion#52]
## Background
In order to run training and calculate target parameter values, the target parameter of specific mesh elements must have the capability to be perturbed. The `changeMaterial` function in `Mesh` will provide this capability. Given the `id` of the elements that will be perturbed, the value at which the parameter will be updated, and the `target_parameter` of type `rbm::Parameter` this function should determine all the mesh elements that need to be updated and call their `setParameter` function. This determination should be done on the `_course_grid` assuming the `MeshElements` in the `_fine_grid` will also be updated. This must be tested as well. The `setParameter` function in `MeshElement` will call the `setParameter` function of `Material`. `Material`'s `setParameter` function has yet to be implemented. This should take the same values as `changeMaterial` and should determine the parameter to change using the `target_parameter` and the enumerations in `rbm::Parameter`.

## Tasks
- [x] Implement the `changeMaterial` function in `Mesh`
- [x] Implement the `setParameter` function in `Material`
- [x] Test `setParameter`
- [x] Test `changeMaterial` for correctness in the `_course_grid` and in the `_fine_grid`

## Definition of Done
The functions are implemented and correctly update the `MeshElements` of the `_course_grid`. The pointers of the `_fine_grid` should be checked for the update as well. All tests should pass.
